### ISSUE TITLE
unable to return to previous states 

### ISSUE THREAD

**Issue by albarqmaria** [albarqmaria/geome-ui#2]
when trying to return to 'about' and 'query' pages, or click the back button, (after using the 'sign in' link from src/app/components/project-selector-dialog/projectSelectorDialog.html) the view is stuck on the login page 
![screen shot 2018-07-14 at 10 48 55 am](https://user-images.githubusercontent.com/35155534/42722880-2ecd023c-8754-11e8-8351-6a899e5b1ed2.png)

**Comment by rodney757** [comment]
this is happening b/c you are redirecting a user in the middle of a state transition hook and then router breaks.

The projectSelectorDialog is opened via the `projectView.hook`. when you call `$mdDialog.cancel()` it will reject the promise in `projectView.hook` which will in turn attempt to transition to another state. For some reason this causes the router to break.

The way to fix it is to call `$mdDialog.cancel` passing along a transition [target](https://ui-router.github.io/ng1/docs/latest/classes/state.stateservice.html#target). Then in the hook `catch` function, if a `TargetState` is returned, you return that, otherwise you execute the existing logic.

something like:

```
this.$mdDialog.cancel(this.$state.target('login'));
```

you can even bind the `trans.to` state name & params to the `project-selector-dialog` in the [projectHook](https://github.com/mariadeck/geome-ui/blob/develop/src/app/projectView.hook.js#L44). 

Then return the targetState like:
```
this.$mdDialog.cancel(this.$state.target('login', {
      nextState: this.toStateName,
      nextStateParams: this.toStateParams,
}));
```

and after login, the dialog box will open again and take the user where they originally wanted to go

**Comment by rodney757** [comment]
also, it may be better to place this 'login' link in the `projectSelector` dropdown menu header. This way it will appear when you open the projectSelector from the header on the website, and not only from the dialog
