### ISSUE TITLE
Issue #54

### ISSUE THREAD

**Issue by albarqmaria** [albarqmaria/geome-ui#3]
Issue #54 now looks like 
![screen shot 2018-07-14 at 12 31 47 pm](https://user-images.githubusercontent.com/35155534/42723661-6c343e02-8762-11e8-99b8-f9f4cb5793bf.png)

rather than
![screen shot 2018-07-14 at 12 05 21 pm](https://user-images.githubusercontent.com/35155534/42723665-73f8b29e-8762-11e8-94a0-779f63c78d48.png)

I'm not sure why the css was affected... would you like me to edit it to look like the previous version?

**Comment by rodney757** [comment]
I think this is a question for me? It's better to create issues in the geome-ui repo instead of your fork.

It's because the about page route contained `parent: 'containerPageView',`.

By default, the page if full screen. If you specify `containerPageView` as a parent to a route, the content will be displayed in a container (2nd version). If you specify `projectView` as the parent, then you have the sidebar on the left, like all the `workbench` views
